# Generated by Django 5.1.2 on 2024-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='idioma',
            field=models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Italiano', 'Italiano'), ('Francês', 'Francês'), ('Espanhol', 'Espanhol'), ('Alemão', 'Alemão')], max_length=9),
        ),
    ]
