# Generated by Django 5.1.2 on 2024-10-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livros_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='idioma',
            field=models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Italiano', 'Italiano'), ('Francês', 'Francês'), ('Espanhol', 'Espanhol'), ('Alemão', 'Alemão')], default='Português', max_length=9),
        ),
        migrations.AlterField(
            model_name='livros',
            name='numeroPaginas',
            field=models.PositiveIntegerField(max_length=255),
        ),
    ]
